### ISSUE TITLE
Window 1-10 commands are not working as intended

### ISSUE THREAD

**Issue by Tehnix** [Tehnix/spaceneovim-layers#1]
It seems the mappings for `SPC 0-9` (i.e. opening window 1-10) are currently not mapping correctly. Instead they are triggering a search, whereas they should be calling `1 wincmd w` to go to the window given by the number.

**Comment by lowski** [comment]
@Tehnix what do you think about disabling it on windows but keeping it on Linux / Unix as it is? At least temporary until properly fixed.

**Comment by Tehnix** [comment]
Ah, it actually got nothing to do with the OS, but that `SpaceNeovimMap('0', 'window 1', '1 wincmd w')` would trigger a search highlight, and not execute the correct command :/

**Comment by Tehnix** [comment]
This was resolved with 25ee357fa0df82cc00969483cbed0902a36af733. The bindings are now under `SPC w 0-9`.
