### ISSUE TITLE
woop

### ISSUE THREAD

**Issue by Cam1337** [Tehnix/spaceneovim-layers#14]
Not the best place to leave a message, but the only place I can reach you. Is IRC down?

**Comment by Tehnix** [comment]
Hey man! :D
Ye, we kinda went full slack :3 you can check it out at info.codetalk.io and there's also an autoinviter :) (the channel is #lobby-irc)

Ps, let me know when you've seen this, then I'll remove the info from this comment :)

**Comment by Cam1337** [comment]
merp didn't see it, cam@chicago.com if ya wanna email.
