### ISSUE TITLE
Language Server with Python and virtual env

### ISSUE THREAD

**Issue by autoferrit** [Tehnix/spaceneovim-layers#29]
I have the language server setup running and working for php. But I am trying to get it running for python. It seems to be running, but none of the commands work. I think it may be because it is not seeing the required virutal environment for a given project.

Does anyone know how I can specify a virtualenv based on a directory or project I am in?

**Comment by Tehnix** [comment]
Hmm, that should mainly be up to the language server itself (to detect virtualenv). Which one are you using? Might need some additional setup, I can take a look at it :)

**Comment by autoferrit** [comment]
I figured it out last night. I was not launching vim while the env was activated. silly oversight.
