### ISSUE TITLE
A quickjump layer - initial queries

### ISSUE THREAD

**Issue by piggyslasher** [Tehnix/spaceneovim-layers#40]
Hello, I'd like to contribute a [vim-easymotion](https://github.com/easymotion/vim-easymotion) layer. Any input on what you'd like the key bindings to be?

**Comment by Tehnix** [comment]
That would be awesome!

Do you know if there is anything similar in Spacemacs? We aim to strive to as close of a keybinding match as we can, but if it's not present there, then we just make our own :)

I think it would make sense under `SPC s` which is currently `+specs`, but should probably be `+search`. This does bring up where to move testing though 🤔

**Comment by piggyslasher** [comment]
Not sure about Spacemacs, but Spacevim has bound 'f f' to __find file__ which I don't agree with as you can't use `f` to forward-find a character anymore! They have defaulted to use `SPC SPC f <character>' instead - which brings up easymotion. Also - three keystrokes to invoke easymotion doesn't make it any easier :).

`SPC s` makes sense - however how about keeping tests in it's own layer but under 'SPC t' and binding easymotion to `SPC s`? What else do you have in mind for the search layer? I don't believe I have the know how right now to combine layers, but I'll have a look over the next few days. Keep up the good work.

**Comment by Tehnix** [comment]
Sorry for the slow replies lately!

Hmm, yeah it would probably be best to have it on something that's quickly accessible. `SPC t` is current inhabited by `+toggle`.

How about a making it a top-level binding, meaning it activates directly after `SPC` + whatever key, preferably without moving anything we currently have - something like `SPC d`, which is neither used in SpaceNeovim or Spacemacs, and is conveniently on the home row?


Just for easy reference in this discussion, these are the current top-level bindings,

<img width="824" alt="screenshot 2017-12-19 12 54 28" src="https://user-images.githubusercontent.com/1189998/34140131-f9e4ae48-e4bb-11e7-9778-9fbcb1d79455.png">

and Spacemacs, for inspiration,

<img width="903" alt="screenshot 2017-12-19 12 59 46" src="https://user-images.githubusercontent.com/1189998/34140215-881b0aae-e4bc-11e7-93cc-976388acf868.png">

**Comment by Tehnix** [comment]
I've just pushed https://github.com/Tehnix/spaceneovim-layers/commit/32db36af60ec490c57e48fdff44578e663e9e76f, which adds vim-easymotion on `SPC d`, and some other navigation commands under `SPC N`.

Let me know if there's anything missing, and then we can reopen the issue (or just make PRs to change the behaviour 😃 ).

**Comment by ytang** [comment]
Spacemacs (see [doc](http://spacemacs.org/doc/DOCUMENTATION.html#vim-motions-with-avy)) uses `SPC j j` and `SPC j J` for 1-char and 2-char jumps, respectively. I suggest we use the same, and also map `SPC j w` to `easymotion-overwin-w`, `SPC j l` to `easymotion-overwin-line`, etc.

**Comment by Tehnix** [comment]
@ytang I've made an initial PR at https://github.com/Tehnix/spaceneovim-layers/pull/45, let me know if you have any comments or wishes for more there!
