### ISSUE TITLE
Use idiomatic locations for viminfo (shada) and undodir

### ISSUE THREAD

**Issue by ytang** [Tehnix/spaceneovim-layers#47]
By default, Neovim stores viminfo (a.k.a. shada) at `~/.local/share/nvim/shada/main.shada` and undodir at `~/.local/share/nvim/undo` (see `:h shada-file-name` and `:h undodir`). FYI, Neovim has clear distinction on the usage of `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` (see neovim/neovim#3470). Would you please not overwrite them with non-idiomatic paths in [+core/sensible](https://github.com/Tehnix/spaceneovim-layers/blob/a6111947cb881175be1c3b1df932632b477bb557/layers/%2Bcore/sensible/config.vim#L31-L49), or provide an option of just using the default paths? Thanks!

**Comment by Tehnix** [comment]
Sure! I hadn't heard about those conventions before, but would love to be compliant to whatever existing conventions are there :)

So I take it that undo should go to `$XDG_DATA_HOME/nvim/undo` if `$XDG_DATA_HOME` is set, else `.local/share/nvim/undo`, and the same for viminfo?

Would you be up for a PR on this?

**Comment by ytang** [comment]
Correct. I've created a minimal PR to remove the custom paths, so that Neovim would just use the default ones.

Note that this change is backward-incompatible in a sense. You would lose your existing viminfo and persistent undo unless you manually move the files from the previous locations.
