### ISSUE TITLE
Been getting an error from supertab on multiple machines with a fresh install of spaceneovim

### ISSUE THREAD

**Issue by vviikk** [Tehnix/spaceneovim-layers#57]
i.e.
```
$ nvim
Error detected while processing /home/user/......supertab/plugin/supertab.vim:
line 1000:
E475: Invalid argument: pumvisible() ? "\<C-P>" : "\<S-Tab>"
Press ENTER or type command to continue
```
Seems like the dev of Supertab has gone awol since 2017 as you can see in this issue:
https://github.com/ervandew/supertab/issues/185

Using this fork solves the error:
https://github.com/metalelf0/supertab

**Comment by Tehnix** [comment]
Thanks for catching this! I've updated the layer to pull from the fork instead :)
