### ISSUE TITLE
Question about SpFileTypeBind 

### ISSUE THREAD

**Issue by beajeanm** [Tehnix/spaceneovim-layers#58]
Hi,

I've just discovered this project, and thanks for making my configuation simpler, and more poweer at the same time! 😄 

SpFileTypeBind/Map/NMap are all marked as broken in the documentation.
Is that something that's being worked on?
What would be a good workaround to have language specific shortcuts?

Thanks

**Comment by Tehnix** [comment]
Hmm, I think the documentation might be out-of-date for this. At least, `SpFileTypeNMap` is what is currently used in the language layers to have the behaviour of `SPC m` being language specific all the time.

Check out https://github.com/Tehnix/spaceneovim-layers/blob/master/layers/%2Blang/elm/config.vim and https://github.com/Tehnix/spaceneovim-layers/blob/master/layers/%2Blang/haskell/config.vim for an example of how it's used :)
