### ISSUE TITLE
update-spaceneovim-layers isn't working on stable release of neovim(0.1.5)

### ISSUE THREAD

**Issue by alexanderjeurissen** [Tehnix/spaceneovim-layers#6]
So I noticed on another machine that is running the latest stable release of Neovim (0.1.5) that the function that is supposed to update the spaceneovim layers results in a runtime error. The screenshot below shows the result of invoking the corresponding keybinding `feU`

![screen shot 2016-10-22 at 00 36 53 1](https://cloud.githubusercontent.com/assets/1220084/19614192/b5ac3f78-97f2-11e6-95f6-b7e5ed1d524d.png)

It seems that the `nvim_buf_set_lines` function isn't present in the current stable release of Neovim. It works fine however in 0.1.6, which is the unstable release. I'm not sure what part of the target audience of spaceneovim is actually using the HEAD version of Neovim but that is definitely something to keep in mind whilst adding new features.

**Comment by lowski** [comment]
I'm using `0.1.7` and didn't notice any problems with updating layers. @alexanderjeurissen do you still have that issue?

**Comment by Tehnix** [comment]
Stable is now at `0.1.7` and it should be working, so I'm closing this since it should be working now.
